title:              
email:              
description:        
author:             GOSPL
baseurl:            "webpage"
url:                "https://rugilemat.github.io"

# Social Profiles
twitter_username:   
github_username:    
facebook_username:  
linkedin_username: 

# Add your google-analytics ID here to activate google analytics
google_analytics:   

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-gist
  - jekyll-sitemap
  - jekyll-twitter-plugin
  ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
